### ISSUE TITLE
add gene removal icons to DNA component

### ISSUE THREAD

**Issue by joshdmiller** [StoryShop/app#88]
## Overview

Add a right "trash" icon that appears on hover to each [character gene](https://github.com/StoryShop/app/blob/e02402b8ef93539565f55e2b9fdd5f10964fb628/src/components/characters/dna/index.js#L160), dispatching the `deleteGene` callback on click with the character ID and the index of the gene to delete.

Add or update the component story.

**Comment by chrisharrington** [comment]
Edit: you can disregard this; I figured it out enough to move forward.

@joshdmiller Do you happen to have a list of props that the DNA component is expecting? I see that a gene is one of them. What properties does the gene class have? I'm looking to create a story for the DNA component and want to make sure I have all the right props.
